### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by thomaschackostatkraft** [microsoft/vscode-apimanagement#100]
While trying to open some APIs in Open Editor, we get this error. 

Action: azureApiManagement.showApi
Error type: Error
Error Message: Cannot read property 'replace' of undefined

Version: 0.1.3
OS: win32
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
OpenApiEditor.<anonymous> extension.bundle.js:262:5370469
a extension.bundle.js:262:5369472
```

</details>

**Comment by miaojiang** [comment]
Thank you. Please re-open if this issue persists.
