### ISSUE TITLE
error when creating demo instance on API management

### ISSUE THREAD

**Issue by azzolin** [microsoft/vscode-apimanagement#113]
Repro steps:

1.
2.

Action: azureApiManagement.createService
Error type: Error
Error Message: Error "parameters.sku.capacity cannot be null or undefined." occurred in serializing the payload - {
  "location": "westus",
  "sku": {
    "name": "Consumption"
  },
  "publisherEmail": "gustavo.azzolin@outlook.com",
  "publisherName": "gustavo.azzolin@outlook.com"
}.

Version: 0.1.4
OS: win32
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
ApiManagementService.b [as _beginCreateOrUpdate] extension.bundle.js:262:4659083
ApiManagementService.beginCreateOrUpdate extension.bundle.js:262:4680725
ApiManagementService.l [as _createOrUpdate] extension.bundle.js:262:4631690
extension.bundle.js:262:4676514extension.bundle.js:262:4676514
ApiManagementService.createOrUpdate extension.bundle.js:262:4676492
ServiceCreateStep.<anonymous> extension.bundle.js:262:5489381
extension.bundle.js:262:5488878extension.bundle.js:262:5488878
n extension.bundle.js:262:5488655
ServiceCreateStep.execute extension.bundle.js:262:5489131
AzureWizard.<anonymous> extension.bundle.js:262:681393
o extension.bundle.js:262:679283
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EdiFirst** [comment]
@RupengLiu Are you closed my issue and this one related to mine too. But did you solve the problem?
