### ISSUE TITLE
Issue when extracting API

### ISSUE THREAD

**Issue by your-azure-coach** [microsoft/vscode-apimanagement#119]
Hi,

I want to extract an API (right click on API) - something that succeeded before - but I get the exception "**NET Framework 2.1 not installed**. (.NET Framework 4.8 is installed)"  The extension lets me log in with Azure CLI and then I get this exception.  These are the traces:

```
Opening "xxx-api-api-arm.json"...
Running command: "az login"...
You have logged in. Now let us find all the subscriptions to which you have access...
The following tenants don't contain accessible subscriptions. Use 'az login --allow-no-subscriptions' to have tenant level access.
xxx
[
  {
    "cloudName": "AzureCloud",
    xxx
]
Finished running command: "az login".
Running command: "az account set --subscription xxx"...
Finished running command: "az account set --subscription xxx".
```

![apim-extension-error](https://user-images.githubusercontent.com/66182046/92927732-5f2a9f80-f43e-11ea-84d9-bd3f1b02f39c.png)

Any idea what's going  wrong?

Thank you

**Comment by miaojiang** [comment]
cc @RupengLiu

**Comment by your-azure-coach** [comment]
Gentle ping @RupengLiu 

Thank you!

**Comment by renebik** [comment]
Any update on this?

**Comment by miaojiang** [comment]
@RupengLiu please comment.

**Comment by colinbeales** [comment]
Same issue and .NET Core 2.1 is on my machine (even went back and put 2.1.0 vanilla on just to check)

dotnet --list-runtimes
Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by enochjlee** [comment]
See my comment here:
https://github.com/microsoft/vscode-apimanagement/issues/146#issuecomment-764064487

**Comment by miaojiang** [comment]
Closing this one. Will address in #146.
