### ISSUE TITLE
Issue in import OpenAPI link in APIM.

### ISSUE THREAD

**Issue by pradnya984shedge** [microsoft/vscode-apimanagement#122]
Repro steps:

1.create New Api in API management extention for visual source code
2. importing OPENAPI as swagger.json.

Action: azureApiManagement.importOpenApiByLink
Error type: Error
Error Message: Cannot read property 'length' of undefined

Version: 0.1.5
OS: win32
Product: Visual Studio Code
Product Version: 1.49.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:262:3546870extension.bundle.js:262:3546870
a extension.bundle.js:262:3545381
```

</details>

**Comment by KaiWalter** [comment]
Seems like an issue with the swagger.json. @pradnya984shedge : you're willing to share this file?

**Comment by miaojiang** [comment]
+1 @pradnya984shedge can you share the file?

**Comment by s-leonard** [comment]
Im getting the same issue and it doesn't happen when importing the same open api spec in the Azure Portal

**Comment by miaojiang** [comment]
@s-leonard would you be able to share the open api spec?

**Comment by s-leonard** [comment]
I found the reason it breaks. If the spec is missing the servers section it breaks. It doesn't break when you import from the portal though. I'm not actually sure why the servers section is missing on my apps service deployments. I need to check that, but the portal import handles this. 

`
"servers": [
      {
        "url": "https://apilocation.com"
      }
    ],
`
