### ISSUE TITLE
Element with id is already registered

### ISSUE THREAD

**Issue by jenspalmqvist** [microsoft/vscode-apimanagement#127]
When opening APIs I get this list:

![image](https://user-images.githubusercontent.com/52400171/94522697-556fad00-0230-11eb-85e5-7aff970c23d2.png)

When I try to click "Load more" I get this error message:
"Element with id /subscriptions/.../auth-api;rev=21 is already registered"

Any suggestions on what might be the issue here? There are as of right now 71 revisions to that API.

**Comment by SteppingRazor** [comment]
@jenspalmqvist I am also experiencing this issue. Basically it happens when there is a lot of APIs inside APIM with many revisions. This error and lack of filtering makes this extension basically unusable.

**Comment by KaiWalter** [comment]
@SteppingRazor @jenspalmqvist how much are "many revisions"? Maybe I can look into it.

**Comment by jenspalmqvist** [comment]
@KaiWalter for me it's 77 revisions on the Auth-API as of right now. I saw @SteppingRazor made a suggestion for a "show only current" filter, and had the idea of a setting for "Show only x latest revisions".

**Comment by KaiWalter** [comment]
@SteppingRazor @jenspalmqvist - I created an empty instance and populated it with 20 APIs and 80 revisions of API-5

```PowerShell
for($i = 0;$i -lt 20; $i++) { New-AzApiManagementApi -Context $ctx -Name $("API-"+$i) -Description $("API "+$i) -ServiceUrl "http://localhost" -Path $("api/"+$i) -Protocols "Https" }

$api = Get-AzApiManagementApi -Context $ctx -Name "API-5" | ?{$_.ApiRevision -eq 1}; for($i = 2;$i -lt 80; $i++) { New-AzApiManagementApiRevision -Context $ctx -ApiId $api.ApiId -ApiRevision $i -ApiRevisionDescription $i -SourceApiRevision $($i-1)  }
```

but was not able to reproduce the error with current master commit 7e9b71f588e6a5c3d606c0a3881afa154fd7c11c.

**Comment by miaojiang** [comment]
@RupengLiu to take a look. 

In the meanwhile, we are working on creating a better experience working with an instance with many revisions of APIs.

**Comment by miaojiang** [comment]
Please reopen if the issue remains in the latest extension version.
