### ISSUE TITLE
implement filtering of APIs

### ISSUE THREAD

**Issue by KaiWalter** [microsoft/vscode-apimanagement#132]
We use API Management in an enterprise environment with more than 200 APIs. Finding the API to be edited within the explorer is cumbersome as additional API entries have to be loaded several times and the chance is high that one misses exactly the API in question.

As this does not seem to be a mainstream requirement I would want to start to implement this feature and would like to use this issue to discuss implementation approach and things I need to consider.

### Suggestion:

2 entries are added to the **APIs** context menu to allow adding and resetting a filter:

![2020-10-22 APIM VSC explorer filter APIs](https://user-images.githubusercontent.com/7418323/96889001-77063200-1486-11eb-8fbd-a4c0308f2138.png)

Clicking on **Filter APIs** would open a input pop-up to allow the user to enter a part of the APIs `displayName` to be filtered for.  List of APIs is then refreshed and only APIs where `displayName` contains the entered value.

Clicking on **Reset filter** would clear the filter and refresh the list.

**Comment by SteppingRazor** [comment]
@KaiWalter 
Yes. For APIMs that have large amount of APIs, APIs versions and revisions using this extension is very problematic or even impossible to use (#127)
I was also thinking about a solution for this, to add filtering of any kind. Of course the filter textbox is the ultimate thing but I was stuck how can I put the filter textbox directly on the tree under APIM instance (Ideally with little filter toggle button), somehting like this:
![image](https://user-images.githubusercontent.com/12941076/96902366-b8054300-1494-11eb-9ef4-2ab5cf1c89f8.png)

Anyway I had another idea:
This extension loads 20 items at one time. Which would be ok but it counts revisions as well. So if API has lets say 25 revisions, it will load only this API and user has to click "load more" many times to get other APIs. I came up with "show only current revision" button which will either load all revisions for API or only the current one.
Before:
![image](https://user-images.githubusercontent.com/12941076/96901096-1d583480-1493-11eb-8593-5f7ee4754f1b.png)
Filter:
![image](https://user-images.githubusercontent.com/12941076/96900723-b2a6f900-1492-11eb-85de-d61b3bc1cc8a.png)
After:
![image](https://user-images.githubusercontent.com/12941076/96900940-ed109600-1492-11eb-8dc5-6156032800b7.png)

It kind of work but the code is ugly (I dont have experience of developing vs code extensions). But I would like to hear your opinion about it.

**Comment by KaiWalter** [comment]
@SteppingRazor - thanks for your additional input. I was able to piece it together quickly with a "standard" VS Code input box in my PR #133 
Fortunately the underlying API request etc. just needed a slight modification to consider the filter.

**Comment by SteppingRazor** [comment]
@KaiWalter 
I've just checked your change. It works great. If the textbox directly in the tree is not possible I would like to see the text by which APIs are currently being filtered or icon that indicates the filter is enabled. Maybe on APIs level?

**Comment by KaiWalter** [comment]
@SteppingRazor changing the label from `APIs` to `APIs (filter by xyz)` and back on reset seems feasible for my limited knowledge of TypeScript and the codebase. Also I want to bring in the filter symbol next to the `APIs` label.

**Comment by SteppingRazor** [comment]
@KaiWalter 
Yeah, I'm just brainstorming here. I just think it would be nice to have some indicator saying that at the given moment APIs are filtered or not. 
Anyway I would like to see this filter on the next release - it is very useful, hope it gets approved.

**Comment by KaiWalter** [comment]
@SteppingRazor 
Having a symbol like filter on the explorer `APIs` node does not seem to be a concept used in the extension. Hence I would skip it.
Just adding this extension to the `APIs` label causes some strange side effects. Found this 

>**Note** that when labels change, ids will change and that selection and expansion state cannot be kept stable anymore.

For the moment I better leave the PR as it is. Maybe some other folks have suggestions how to achieve this indicator, that the list is filtered.
