### ISSUE TITLE
Debug Gateway address Url was hard coded, will not work for custom domain 

### ISSUE THREAD

**Issue by weiqingbc** [microsoft/vscode-apimanagement#142]
function getDebugGatewayAddressUrl(serviceName: string): string {
    return `wss://${serviceName}.azure-api.net/debug-0123456789abcdef`;
}
This would not work for customers who have custom domain configured, some customer's environment blocks *.azure-api.net , only their own custom domains were allowed to go through.

**Comment by weiqingbc** [comment]
cx downloaded 0.1.8 and reported back it didn't work still, please reopen this

**Comment by miaojiang** [comment]
@RupengLiu  please check.

**Comment by weiqingbc** [comment]
@RupengLiu I submitted this item for our customer, please let me know how soon we can fix this.

**Comment by tslavik** [comment]
There is still some issue. I have accessible only my own domain but as you can see in debug there is still *azure.api.net 
`From client: launch({"type":"apim-policy","request":"launch","name":"Attach to APIM","stopOnEntry":true,"gatewayAddress":"wss://correctDomain/debug-0123456789abcdef","managementAddress":"https://management.azure.com//subscriptions/.../resourceGroups/mcons-apim/providers/microsoft.apimanagement/service/mcons-apim","subscriptionId":"...","operationData":"GET **https://mcons-apim.azure-api.net**/health HTTP/1.1\nOcp-Apim-Subscription-Key: ....\nOcp-Apim-Debug: ....\nOcp-Apim-Trace: true\n","fileName":"mcons-apim-healthcheck-api-healthcheck.http","__sessionId":"86f1fc04-d530-4760-8af6-11626810de89"})
To client: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"Can't connect to gateway: Unexpected server response: 404."}}
Can't connect to gateway: Unexpected server response: 404.
`
Bolded the wrong generated domain for the request
