### ISSUE TITLE
APIM policy upload failed from VSC

### ISSUE THREAD

**Issue by wadeem** [microsoft/vscode-apimanagement#145]
Repro steps:

1.
2.

Action: azureApiManagement.operationPolicyEditor.onDidSaveTextDocument
Error type: Error
Error Message: Error: "ValidationError" - "Error in element 'set-header' on line 19, column 7: The element 'set-header' cannot contain text. List of possible elements expected: 'value'." 

Version: 0.1.7
OS: win32
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
OperationPolicyEditor.<anonymous> extension.bundle.js:1:375129
a extension.bundle.js:1:373796
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by RupengLiu** [comment]
@wadeem it seems that the repro step is empty

**Comment by RupengLiu** [comment]
@wadeem it fails due to the policy validation, please check the "set-header" policy usage
