### ISSUE TITLE
Azure API Management Extension require .netframework 2.1

### ISSUE THREAD

**Issue by chetanmangsuli84** [microsoft/vscode-apimanagement#146]
Hello,

I am trying to use Azure API Management Extension on mac I get the error message "NET framework 2.1 not installed. Please go to 'https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=win10-x64' to download" 

Source : Azure API Management(Extension)
when extracting the API using this extension whether can we use this extension is supported on mac.

Thanks,
chetan

**Comment by enochjlee** [comment]
I found a work around for this:
https://github.com/microsoft/vscode-apimanagement/blob/7033cc3762036dc73e0763348b6908497020c671/src/utils/dotnetUtils.ts#L56
is calling `dotnet --list-sdks` not `dotnet --list-runtimes`
so you have to install a .NET Core SDK, not a runtime.
https://dotnet.microsoft.com/download/dotnet-core/2.1

I installed the SDK and it started working.
https://github.com/microsoft/vscode-apimanagement/blob/7033cc3762036dc73e0763348b6908497020c671/src/utils/dotnetUtils.ts#L42
should be something more descriptive, i.e. 
`const message: string = localize('dotnetNotInstalled', 'You must have a .NET Core SDK v2.1.x CLI installed to perform this operation.');`

**Comment by your-azure-coach** [comment]
Thanks a lot @enochjlee , this worked for me!

**Comment by miaojiang** [comment]
Thank you!

**Comment by narcisradoi** [comment]
this is still happening - pointing to the runtime link instead of the SDK - it should be pointing to https://dotnet.microsoft.com/en-us/download/dotnet/2.1 - but its pointing to https://dotnet.microsoft.com/en-us/download/dotnet/2.1/runtime

**Comment by akishaha** [comment]
> I found a work around for this:
> 
> https://github.com/microsoft/vscode-apimanagement/blob/7033cc3762036dc73e0763348b6908497020c671/src/utils/dotnetUtils.ts#L56
> 
> 
> is calling `dotnet --list-sdks` not `dotnet --list-runtimes`
> so you have to install a .NET Core SDK, not a runtime.
> https://dotnet.microsoft.com/download/dotnet-core/2.1
> I installed the SDK and it started working.
> 
> https://github.com/microsoft/vscode-apimanagement/blob/7033cc3762036dc73e0763348b6908497020c671/src/utils/dotnetUtils.ts#L42
> 
> 
> should be something more descriptive, i.e.
> `const message: string = localize('dotnetNotInstalled', 'You must have a .NET Core SDK v2.1.x CLI installed to perform this operation.');`

This workaround worked for me too.
