### ISSUE TITLE
Getting below error while debugging API using APIM extension.

### ISSUE THREAD

**Issue by saikiran-karumuri-by** [microsoft/vscode-apimanagement#151]
Action: azureApiManagement.initializeExtensionWorkspaceFolder
Error type: Error
Error Message: Failed to run "dotnet" command. Check output window for more details.

Version: 0.1.8
OS: darwin
Product: Visual Studio Code
Product Version: 1.52.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:1:313555
o extension.bundle.js:1:312584
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by miaojiang** [comment]
@RupengLiu

**Comment by RupengLiu** [comment]
can you provide the steps to repro the issue?
