### ISSUE TITLE
Option to not clear templates folder when using Extract Service/Api

### ISSUE THREAD

**Issue by lmrisdal** [microsoft/vscode-apimanagement#155]
I'm trying to set up a solution where users can either use the Extractor tool from commandline or use the Extract Service/Api functionality for extracting apis. The way this extension works now is by first clearing the "templates" folder and then running extraction. Is there a way to make it not do this?

**Comment by miaojiang** [comment]
This is by design at the moment. The workaround would be choosing another folder if you'd like to retain existing files.
