### ISSUE TITLE
"Entry not found in cache" while editing Azure API Management

### ISSUE THREAD

**Issue by freeone3000** [microsoft/vscode-apimanagement#158]
Repro steps:

1. Use Azure API Management Extension
2. Open multiple policy tabs
3. Make edit, attempt to save
3. Error message appears

Action: azureApiManagement.operationPolicyEditor.onDidSaveTextDocument
Error type: Error
Error Message: Entry not found in cache.

Version: 0.1.8
OS: win32
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
OperationPolicyEditor.<anonymous> extension.bundle.js:1:375681
a extension.bundle.js:1:374348
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by RupengLiu** [comment]
This is an upstream bug by AAD. Link: https://github.com/microsoft/vscode-azure-account/issues/53, we are waiting for upstream to fix it
