### ISSUE TITLE
Cannot edit versioned APIs using VS Code APIM extension

### ISSUE THREAD

**Issue by tyson-benson** [microsoft/vscode-apimanagement#161]
Repro steps:

1. Under the API management explorer in the VS Code Azure menu, I right-clicked on an API v1 (child node of the API version set) and selected the "Edit OpenAPI" context menu item.
2. I observed the reported error message in the VS Code console log.

I found that when I attempt to Edit OpenAPI for non-versioned API's created using the VS code extension works just fine. I'm assuming creating and working with versioned API's is not well supported by this extension at this time.

Action: azureApiManagement.showApi
Error type: Error
Error Message: Cannot read property 'replace' of undefined

Version: 0.1.8
OS: win32
Product: Visual Studio Code
Product Version: 1.53.0
Language: en

<details>
<summary>Call Stack</summary>

```
OpenApiEditor.<anonymous> extension.bundle.js:277:13330
a extension.bundle.js:277:12312
```

</details>

**Comment by tyson-benson** [comment]
Looks like this has already been reported by #154

**Comment by RupengLiu** [comment]
Fixed
