### ISSUE TITLE
Debug Policy feature not working

### ISSUE THREAD

**Issue by SteppingRazor** [microsoft/vscode-apimanagement#168]
Extension version: 0.1.8
VS Code version: 1.53.2

Following [documentation](https://docs.microsoft.com/en-us/azure/api-management/api-management-debug-policies#initiate-a-debugging-session) states that right after clicking "Start debugging session" on the operation, extension should open new editor that will allow to send HTTP request and then the policy code where it should be possible to set breakpoints.

The problem is right after clicking "Start debugging session" nothing happens. The only thing I can see in the "Debug console" is this (I have xxx'ed out sensitive data):
`From client: initialize({"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"apim-policy","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us","supportsProgressReporting":true,"supportsInvalidatedEvent":true})
To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"supportsConfigurationDoneRequest":true,"supportsRestartRequest":false,"supportsRestartFrame":false}}
From client: launch({"type":"apim-policy","request":"launch","name":"Attach to APIM","stopOnEntry":true,"gatewayAddress":"wss://xxx.azure-api.net/debug-0123456789abcdef","managementAddress":"https://management.azure.com//subscriptions/xxx/resourceGroups/xxx/providers/microsoft.apimanagement/service/xxx","subscriptionId":"xxx","operationData":"HEAD https://xxx.azure-api.net/echo/resource HTTP/1.1\nOcp-Apim-Subscription-Key: xxx\nOcp-Apim-Debug: xxx\nOcp-Apim-Trace: true\n","fileName":"xxx.http","__sessionId":"xxx"})`

And that's it - no further logs. If it makes any difference the API is just default Echo-Api. Also the APIM I'm using is brand new Developer instance with only one API and without any gateways (accessible from outside). 
"Test operation" functionality from this extension is working just fine. 

Any ideas what can be wrong?

**Comment by RupengLiu** [comment]
Hi @SteppingRazor , previously, there is a bug in backend that breaks this feature, we have updated the vscode extension, please reinstall to have this fix

**Comment by SteppingRazor** [comment]
Hi, @RupengLiu 
Reinstall what? I do not see the new version of the extension. The latest is still 0.1.8.
I did try to uninstall it and install it again, but it does not help.

**Comment by RupengLiu** [comment]
@SteppingRazor , did you see the operation http editor, you should send request to trigger the policy debugging process

**Comment by SteppingRazor** [comment]
@RupengLiu yeah, as I said nothing opens. This is all I can see when I hit start debugging:
![image](https://user-images.githubusercontent.com/12941076/108771210-a378aa80-755b-11eb-94e4-8a2c50393d9e.png)

**Comment by RupengLiu** [comment]
well, I can't repro from my side, but I can see that the proxy has been connected successfully, you can try write a http file to trigger it, 
![image](https://user-images.githubusercontent.com/29927264/108776647-84f0c000-7517-11eb-9eef-94b12f7d5429.png)
if it still not work, it should be backend issue

**Comment by SteppingRazor** [comment]
@RupengLiu 
With the recent update to version 1.0.0 it works.
