### ISSUE TITLE
error during try create a apim from vscode

### ISSUE THREAD

**Issue by felipementel** [microsoft/vscode-apimanagement#177]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureApiManagement.createService
Error type: ServiceAlreadyExists
Error Message: Api service already exists: apim-test

Version: 1.0.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.54.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:16:56706
extension.bundle.js:16:293514extension.bundle.js:16:293514
processTicksAndRejections task_queues.js:97:5
```

</details>

**Comment by miaojiang** [comment]
Hi @felipementel, as the error message indicated, the name of the instance has already been taken.

**Comment by felipementel** [comment]
@miaojiang 

yes, i think msg doesn't need to create a crash for you - this whole process of creating the item was from vscode.
maybe the error message can be presented in another way and you would not need to create this item for the team either

**Comment by miaojiang** [comment]
@felipementel got it, makes sense. We will take a look and see how to improve it.
