### ISSUE TITLE
API Revisions not switching correctly

### ISSUE THREAD

**Issue by alzobaydee** [microsoft/vscode-apimanagement#180]
Hi team,
we are experiencing a new but rather strange behavior when switching to a revision from VS Code.

TLDR; The VSCode API Revisions continues to show the current API even when choosing to switch to another revision.

We have one API with two revisions.
Choosing the API Revisions from the context menu (when right-clicking on the API from "API tree" menu" in VS Code)
Switching from rev1 which is _current_ to rev2 it will show on API-name in the API tree that it is API;rev2, but when we open a policy for editing it shows the code from rev1. Even the API-arm-tempFile.json is showing the rev1 template after the revision switch.

Hint: I've just updated my VS Code for today

**Comment by miaojiang** [comment]
Thank you. Can confirm I am able to reproduce. @RupengLiu
