### ISSUE TITLE
Use the default  "hostnameConfigurations" properties instead of "gatewayURL" when generating Test Requests 

### ISSUE THREAD

**Issue by ivanthelad** [microsoft/vscode-apimanagement#198]
when generating a test operation against an API, the plugin reference the property "gatewayURL" on the apim service. 
this may not always be desired as a project can also configure a different default custom domain for their apim service gateway. 

Operation generation grabs the gatewayURL
  https://github.com/microsoft/vscode-apimanagement/blob/07a8c123d805ed23fd7521cbfac4894b63c8ba66/src/operationConsole/OperationConsole.ts#L26

An alternative, is to check if the property "hostnameConfigurations" and the value of hostnameConfigurations.proxy.hostName instead. 
`    "hostnameConfigurations": [
      {
        "type": "Proxy",
        "hostName": "mycustomurl.com",
        "encodedCertificate": null,
        "keyVaultId": "https://xxxxx.vault.azure.net/secrets/apim",
        "certificatePassword": null,
        "negotiateClientCertificate": false,
        "certificate": {
          "expiry": "xxxxxx",
          "thumbprint": "xxxxxx",
          "subject": "CN=mycustomurl.com"
        },
        "defaultSslBinding": true
      }
    ],`

The change would need to be done inside the requestURL method 
https://github.com/microsoft/vscode-apimanagement/blob/07a8c123d805ed23fd7521cbfac4894b63c8ba66/src/operationConsole/OperationConsole.ts#L120

**Comment by miaojiang** [comment]
In the latest release, you can use the "set gateway URL" feature (right click on the APIM service instance).
