### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'fullId')

### ISSUE THREAD

**Issue by xdfcgvhbjasd** [microsoft/vscode-apimanagement#249]
Hello,
I am getting the following error when using version 1.0.4 and trying to expand an APIM in VS Code:
`Error: Cannot read properties of undefined (reading 'fullId')`
No specific steps to replicate the issue.
Thanks

**Comment by andreasherkner** [comment]
I can reproduce the same error with version 1.0.4

**Comment by annaji-msft** [comment]
Could you share few more details on the 

ServiceId
Location
Sku

**Comment by andreasherkner** [comment]
This is what the API Management explorer shows:
![image](https://user-images.githubusercontent.com/52561102/175314335-f8bec561-b17f-4467-90c7-bbd2e8b06f9e.png)

There is no further error in any log file, nor in the UI.
My environment is 
![image](https://user-images.githubusercontent.com/52561102/175314873-cdcfe4f0-e422-47c1-9fa4-65e9ef468d33.png)

The extension is working fine in version 1.0.3

**Comment by annaji-msft** [comment]
Could you share what region and sku are these services as well

**Comment by andreasherkner** [comment]
Location is Germany West Central with SKU Consumption

**Comment by annaji-msft** [comment]
@andreasherkner  @xdfcgvhbjasd should be now fixed with latest release of 1.0.5. Please try it out and let us know if you still run into issues. Thanks!

**Comment by xdfcgvhbjasd** [comment]
Looks good now, thanks :)

**Comment by andreasherkner** [comment]
Perfekt 👍 , thanks
