### ISSUE TITLE
Debugging on APIM Dev Tier with VS Code APIM Extension Fails

### ISSUE THREAD

**Issue by JustinMcClain** [microsoft/vscode-apimanagement#309]
Does this occur consistently? YES
Repro steps:

1 - Open DEV instance of APIM in VSCODE

2 - Right click on an API Operation and select "Start Policy Debugging"

3 - Error Pops up "Cannot Read Properties of Undefinied (Reading Primary Key"

![image](https://github.com/microsoft/vscode-apimanagement/assets/95706557/65a3ad6d-c10b-4278-810e-c7cae67ab1b2)

Action: azureApiManagement.debugPolicy
Error type: TypeError
Error Message: Cannot read properties of undefined (reading 'primaryKey')

Version: 1.0.6
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.78.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:479:71081extension.bundle.js:479:71081
OperationConsole.<anonymous> extension.bundle.js:479:71044
fulfilled extension.bundle.js:479:68637
```

</details>

**Comment by fpdutra** [comment]
You can solve this by running this on AZ CLI:
az apim update  --name <API Management Name> -g<Resource Group> --set apiVersionConstraint.minApiVersion=2019-01-01

**Comment by anupriyo6** [comment]
I am also recieving the same error when trying to debug apim policy from VS code.

Is there any workaround or fix for this?

The azure cli command dont work for me
