### ISSUE TITLE
Error: azureApiManagement.importFunctionApp

### ISSUE THREAD

**Issue by FranciscoPrestes** [microsoft/vscode-apimanagement#323]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureApiManagement.importFunctionApp
Error type: ERR_INVALID_ARG_TYPE
Error Message: The "emitter" argument must be an instance of EventEmitter or EventTarget. Received an instance of AbortSignal

Version: 1.0.6
OS: darwin
OS Release: 22.5.0
Product: Visual Studio Code - Insiders
Product Version: 1.82.0-insider
Language: en

**Comment by nbarrasson** [comment]
I got the same issue since last week when I uncollapse the Azure subscription icon.

**Comment by ross-p-smith** [comment]
I get the same error with the latest code base (1.0.6) Crashes when you expand a subscription.
