### ISSUE TITLE
Improved policy authoring experience - Intellisense/completions guidance

### ISSUE THREAD

**Issue by anganti** [microsoft/vscode-apimanagement#37]
Provide guidance on achieving completions/intellisense while editing policy documents.

**Comment by anganti** [comment]
Move documentation here from https://github.com/anganti/apimanagement-policy-authoring#working-with-vscode-extension-one-time-setup

**Comment by anganti** [comment]
Automate the setup steps. Possible commands to Open the folder in workspace and setup/initialize the folder.

**Comment by anganti** [comment]
#45 

![image](https://user-images.githubusercontent.com/42851022/62157079-38082180-b2c1-11e9-89cc-5b5620c0afc3.png)

![image](https://user-images.githubusercontent.com/42851022/62157167-6980ed00-b2c1-11e9-87ce-8e1f58c3a161.png)

![image](https://user-images.githubusercontent.com/42851022/62157308-afd64c00-b2c1-11e9-982b-d153de85bb18.png)

![image](https://user-images.githubusercontent.com/42851022/62157457-10fe1f80-b2c2-11e9-8f4c-022a77d4d8a3.png)

**Comment by UawThompson1** [comment]
)

**Comment by joelwembo** [comment]
I was looking for an insighful tool for Implementing policy authoring for our cloud projects. very helpful indeed
