### ISSUE TITLE
Error uploading updated openapi document for Function App API

### ISSUE THREAD

**Issue by jpandersen87** [microsoft/vscode-apimanagement#38]
I'm sure the source of this issue is that the ARM information on the function API does not include the serviceUrl property unlike the others. Not really sure where that metadata is stored since even logic apps use the property.

Repro steps:

1. Create/Use a function app and corresponding function (in my scenario a javascript v2)
2. Import function into APIM instance using Function App shortcut in API section (azure portal)
3. In vscode-apimanagement, navigate to the new API instance and edit the openapi document via right-click context menu
4. Click the button to upload the document after saving

Action: azureApiManagement.apiEditor.onDidSaveTextDocument
Error type: Error
Error Message: Internal error: Expected value to be neither null nor undefined: serviceUrl

Version: 0.1.1
OS: win32
Product: Visual Studio Code
Product Version: 1.36.0
Language: en

<details>
<summary>Call Stack</summary>

```
OpenApiEditor.<anonymous> extension.bundle.js:262:2686788
o extension.bundle.js:262:2684695
```

</details>

**Comment by anganti** [comment]
Thank you for reporting. Will take a look at the issue.

**Comment by anganti** [comment]
Seems to be a issue happening in the portal too 
![image](https://user-images.githubusercontent.com/42851022/62235757-7addfe00-b382-11e9-8952-a18b9a931218.png)

**Comment by fab66m** [comment]
I experienced the same error. The workaround that worked for me was to specify a Web Service URL once  using Import-AzApiManagementApi and specifying "-ServiceUrl". In my case the APIM service connects to a Service Fabric App, so the actual value is not needed and ignored anyway. From that point on I could update APIs out of VSC without this error message. Maybe this works also for function apps.

> I'm sure the source of this issue is that the ARM information on the function API does not include the serviceUrl property unlike the others. Not really sure where that metadata is stored since even logic apps use the property.
> 
> Repro steps:
> 
> 1. Create/Use a function app and corresponding function (in my scenario a javascript v2)
> 2. Import function into APIM instance using Function App shortcut in API section (azure portal)
> 3. In vscode-apimanagement, navigate to the new API instance and edit the openapi document via right-click context menu
> 4. Click the button to upload the document after saving
> 
> Action: azureApiManagement.apiEditor.onDidSaveTextDocument
> Error type: Error
> Error Message: Internal error: Expected value to be neither null nor undefined: serviceUrl
> 
> Version: 0.1.1
> OS: win32
> Product: Visual Studio Code
> Product Version: 1.36.0
> Language: en
> 
> Call Stack

**Comment by SafwenBenJha** [comment]
Any new updates? Also got the same error with a almost the same scenario:
Repro steps:

1.  Right click on any API
2.  Click "Edit OpenAPI"
3.  Save (even without doing any change)

Action: azureApiManagement.apiEditor.onDidSaveTextDocument
Error type: Error
Error Message: Internal error: Expected value to be neither null nor undefined: serviceUrl

Version: 0.1.2
OS: win32
Product: Visual Studio Code
Product Version: 1.43.2
Language: en

<details>
<summary>Call Stack</summary>

```
OpenApiEditor.<anonymous> extension.bundle.js:262:2693478
o extension.bundle.js:262:2691386
```

</details>

**Comment by RupengLiu** [comment]
Already fixed
