### ISSUE TITLE
error on extension load

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-apimanagement#40]
I'm running on macOS using VS Code's Insider builds. When the extension loads I'm seeing this error pop up:

![image](https://user-images.githubusercontent.com/1487073/61235701-ff761e80-a6ea-11e9-9818-f8110f1f55cb.png)

If I install the C# extension, the error goes away.

**Comment by nbarrasson** [comment]
Same here on a slightly different setup : VSCode with WSL2 backend
