### ISSUE TITLE
Cannot build on macOS

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-apimanagement#41]
MacOS
VS Code Insiders

Clone this repo...

```
git clone https://github.com/microsoft/vscode-apimanagement
cd vscode-apimanagement
npm install
```

and then try to build...

```
~/src/vscode-apimanagement$ yarn build
yarn run v1.12.3
$ tsc -p ./
error An unexpected error occurred: "spawn E2BIG".
info If you think this is a bug, please open a bug report with the information provided in "/Users/chris/src/vscode-apimanagement/yarn-error.log".
info Visit https://yarnpkg.com/en/
```

It looks like this issue: https://github.com/yarnpkg/yarn/issues/5420

If I rename `NOTICE.html` to something else, build works fine.

**Comment by anganti** [comment]
Can you try "npm run build" (or) highlighted steps.

 **Code**: Contribute bug fixes, features, or design changes:
    -   Clone the repository locally and open in Visual Studio Code.
    -   Install [TSLint for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin).
    -   Open the terminal (press `` CTRL+` ``) and run `npm install`.
    -   **To build, press `F1` and type in `Tasks: Run Build Task`.**
    -   **Debug: press `F5` to start debugging the extension.**

**Comment by chrisdias** [comment]
`F1` build task succeeded, then pressing `F5` to launch gives me this:

![image](https://user-images.githubusercontent.com/1487073/61243279-74058900-a6fc-11e9-90bf-29b36c0b8922.png)

**Comment by anganti** [comment]
I have not validated the **Contribution Steps** on MacOS.  Will take a look at this issue.
