### ISSUE TITLE
Enable tracking active item 

### ISSUE THREAD

**Issue by MarkusMeyer13** [microsoft/vscode-apimanagement#42]
Most of my API Management Files just contain a GUID as filename.

> servicename-57f61a470a47690a009a5668-58f87234f79cdf07c428af42.policy.cshtml

If there several policies openend in VS Code, it's not possible to identify which file belongs to the correct policy.

At least tracking the active item by selecting the current policy in the side bar would help

**Comment by miaojiang** [comment]
I believe the GUID is the API ID It's a GUID for older APIs, but we have switched to use more user friendly API ID for APIs created more recently.
