### ISSUE TITLE
I can't 'see' my consumption tier API Management instance

### ISSUE THREAD

**Issue by rtcn2** [microsoft/vscode-apimanagement#48]
I have a consumption tier API Management Instance deployed in my subscription. However when I connect to the subscription in VSCode, the API Management extension doesn't display this instance.
I'm haven't got any outstanding updates, so assume I'm running the latest version of VSCode and the extension.

Please let me know if you need any more information.

**Comment by anganti** [comment]
Could you give us a little more about the APIM instance like serviceid.

**Comment by rtcn2** [comment]
![apimgtinstance](https://user-images.githubusercontent.com/309872/68941002-92f45480-079c-11ea-9f07-8b56e8a1180b.PNG)

Hi,

Not sure what a serviceid is, do you mean the Azure Resource Id?

I have attached a screenshot of the consumption instance I can't see is VSCode. 

Not comfortable with sharing me subscription id and instance name in this public tracker. I can send you details directly if that's required.

Regards.

Rod

**Comment by kwasak** [comment]
Any update on this? I can't see my consumption instance as well. This use to work.

**Comment by rtcn2** [comment]
Not sure what has changed, but I can now see my consumption instances. Still using 0.1.1 of the Azure API Management extension which hasn't been updated since Jun last year.
