### ISSUE TITLE
Missing one or more userOptions when creating new Api

### ISSUE THREAD

**Issue by KaiWalter** [microsoft/vscode-apimanagement#98]
Repro steps:

1. first-time installed vscode-apimanagement extension
2. signed in to Azure / Subscription in API Management explorer
3. command: Azure API Management: Add API to Gateway
4. selected: Subscription / Service / APIs / + Create new API
5. pop up with error message below is displayed

Action: azureApiManagement.addApiToGateway
Error type: Error
Error Message: Missing one or more userOptions when creating new Api

Version: 0.1.3
OS: linux
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
ApisTreeItem.<anonymous> extension.bundle.js:262:858488
extension.bundle.js:262:857101
n extension.bundle.js:262:856878
ApisTreeItem.createChildImpl extension.bundle.js:262:858279
ApisTreeItem.<anonymous> extension.bundle.js:1:334735
extension.bundle.js:1:333931
n extension.bundle.js:1:333708
ApisTreeItem.createChild extension.bundle.js:1:334591
ApisTreeItem.<anonymous> extension.bundle.js:1:337250
extension.bundle.js:1:333931
n extension.bundle.js:1:333708
data extension.bundle.js:1:337199
ApisTreeItem.<anonymous> extension.bundle.js:1:335593
o extension.bundle.js:1:333764
processTicksAndRejections task_queues.js:89:5
```

</details>

**Comment by KaiWalter** [comment]
Had the idea, that maybe it had something to do with me remote SSHing into the linux box, but error also displayed on the Win10 box w/o remote SSH:

Action: azureApiManagement.addApiToGateway
Error type: Error
Error Message: Missing one or more userOptions when creating new Api

Version: 0.1.3
OS: win32
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
ApisTreeItem.<anonymous> extension.bundle.js:262:858488
extension.bundle.js:262:857101extension.bundle.js:262:857101
n extension.bundle.js:262:856878
ApisTreeItem.createChildImpl extension.bundle.js:262:858279
ApisTreeItem.<anonymous> extension.bundle.js:1:334797
extension.bundle.js:1:333993extension.bundle.js:1:333993
n extension.bundle.js:1:333770
ApisTreeItem.createChild extension.bundle.js:1:334653
ApisTreeItem.<anonymous> extension.bundle.js:1:337312
extension.bundle.js:1:333993extension.bundle.js:1:333993
n extension.bundle.js:1:333770
data extension.bundle.js:1:337261
ApisTreeItem.<anonymous> extension.bundle.js:1:335655
o extension.bundle.js:1:333826
```

</details>

**Comment by miaojiang** [comment]
Sorry for the delay. Please re-open if this is still an issue.
